language: cpp
sudo: required
env:
  matrix:
    - VERGE_PLATFORM='linux64'
      #- VERGE_PLATFORM='windows32'
      #- VERGE_PLATFORM='windows64' TODO after 32 works
compiler:
- gcc
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository --yes ppa:bitcoin/bitcoin
  - sudo apt-get update -qq
  - VERGE_TARGET="${VERGE_PLATFORM::${#VERGE_PLATFORM}-2}"
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools libdb4.8-dev libdb4.8++-dev
  - sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils git libboost-system-dev libboost-filesystem-dev libqrencode-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libboost-all-dev libprotobuf-dev protobuf-compiler
  - ./building/${VERGE_TARGET}/requirements.sh

install:
- ./autogen.sh
- ./configure
script:
- make
