name: welcomer-messages

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hi! Thank you for filing an issue. Please be patient before anyone responds.
          Make sure your issue is filled in with as many details as possible.
          Its also recommended to check out previously resolved or closed issues so no duplicates are created.
          There's also the chance the anwser for your issue can be found on one of the XVG wiki/FAQ's.
        pr-message: |
          Thank you for your submitted Pull-Request!
          Please make sure that you've read the CONTRIBUTION.md to prevent unwanted comments. ;)
          Be patient before anyone responds or reviews your Pull-Request.
          Keep in touch with this Pull-Request to make this a quick process!
