name: '[Full Build - MacOS]'

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: git config credential.helper
        run: git config credential.helper

      - name: Brew install base dependencies
        run: brew install automake berkeley-db4 libtool boost@1.76 miniupnpc qt@5 openssl pkg-config python libevent qrencode librsvg && curl -L https://raw.githubusercontent.com/udalov/protobuf261/master/protobuf261.rb > protobuf261.rb && brew install protobuf261.rb

      - name: Brew link dependencies
        run: brew link boost@1.76 qt@5 berkeley-db4

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: ./configure --disable-bench --disable-tests --disable-dependency-tracking --disable-werror --with-gui --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: make
        run: make -j4

      - name: make check
        run: make check -j4

      - name: make .dmg
        run: make deploy

      - name: zip .dmg
        run: zip verge-macos.zip /Users/runner/work/verge/verge/verge-qt.dmg

      - name: upload artifact asset
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name != 'release'}}
        with:
          name: verge-macos.zip
          path: ./verge-macos.zip

      - name: upload release asset
        if: ${{ github.event_name == 'release'}}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./verge-macos.zip
          asset_name: verge-macos.zip
          asset_content_type: application/zip
